= Dedicated Security Components iTC
:showtitle:
:toc:
:imagesdir: images
:icons: font
:revnumber: 0.2
:revdate: 2020-09-15

:iTC-longname: Dedicated Security Components
:iTC-shortname: DSC-iTC
:iTC-email: iTC-DSC@niap-ccevs.org
:iTC-website: https://DSC-iTC.github.io/
:iTC-GitHub: https://github.com/DSC-iTC/cPP

== Introduction
From the CCDB-established Working Group, the {iTC-longname} ({iTC-shortname} for short) was formed. The {iTC-shortname} consists of members of Certification Bodies, labs, vendors and academia working together to create requirements for biometric security testing.

https://www.commoncriteriaportal.org/communities/dedicated_security_components.cfm[Common Criteria Portal {iTC-shortname} Page]

To join the {iTC-shortname}, please send an email to {iTC-email} and include the following in your message: Github handle, Name, Affiliation, Contact Info, Experience, etc.

== Resources related to {iTC-shortname}

[GUIDANCE]
====
{iTC-shortname} Project related resources such as 
====

* link:/cPP/cPPv01.html[cPP] and link:/SD/SDv01.html[SD]
* link:/TD/tech-dec.html[Technical Decisions]
* link:/lifecycle.html[Document Lifecycle & cPP Archives]
* link:/docs/PP-config.html[Allowed-With Configurations]
* link:/library.html[Documentation Library]
* link:/docs/public-review-process.html[Public Review Process for {iTC-shortname}]
* link:/public-review/status.html[Public Review Status]
* {iTC-GitHub}[{iTC-shortname} GitHub repository]

== Current Status
The DSC cPP and SD v1.0 documents have been published and submitted for review by the CCDB for compliance with the CC and CEM.  It can be found on the https://commoncriteriaportal.org/pps/collaborativePP.cfm[Collaborative Protection Profiles (cPP) and Supporting Documents (SD)] page under section "cPPs with SDs that are currently being reviewed by the CCDB for compliance with the CC and CEM" and category of "ICs, Smart Cards and Smart Card-Related Devices and Systems".
