= DSC0003 - Editorial Corrections in Supporting Document
:showtitle:
:imagesdir: images
:icons: font
:revnumber: 1
:revdate: 2023-02-21
:linkattrs:

:iTC-longname: Dedicated Security Components
:iTC-shortname: DSC-iTC
:iTC-email: iTC-DSC@niap-ccevs.org
:iTC-website: https://DSC-iTC.github.io/
:iTC-GitHub: https://github.com/DSC-iTC/cPP/

Published: {revdate}

== Impacted Documents
link:/v1/1.0/cpp_dsc_sd_v1.pdf[SD_DSC_v1.0]

== References
There are multiple editorial changes in this TD. Each one has its own Description and Resolution.

FCS_STG_EXT.1
FDP_SDC_EXT.1
FMT_MOF_EXT.1
FPT_PRO_EXT.1

== Issue Description

=== FCS_STG_EXT.1 Description
There is no support for a "common application developer" in the cPP as mentioned in 2.1.6.1.3.

=== FDP_SDC_EXT.1 Description
There is a typo referencing FCS_COP.1/SK (which does not exist) in 2.2.8.1.3.

=== FMT_MOF_EXT.1 Description
There is a typo referencing FMT_SMF_EXT.1 (which does not exist) in 2.4.1.1.3.

=== FPT_PRO_EXT.1 Description
There is a typo referencing FPT_PHP.1 (which does not exist) in 2.5.4.1.3.

== Resolution

=== FCS_STG_EXT.1 Resolution
The description and tests associated with this selection will be removed.

=== FDP_SDC_EXT.1 Resolution
The reference will be corrected to FCS_COP.1/SKC.

=== FMT_MOF_EXT.1 Resolution
The reference will be corrected to FMT_SMF.1.

=== FPT_PRO_EXT.1 Resolution
The reference will be corrected to FPT_PHP.3.

== SD_DSC_v1.0
The SD is updated as follows (yellow highlights for additions, strikethrough for deletions) per section that is being updated:

*2.1.6.1.3 Test*

The evaluator shall test the functionality of each security function as described below. If the TOE supports both import and generation of keys, the evaluator shall repeat the testing as needed to demonstrate that the keys resulting from both operations are treated in the same manner. The devices used with the tooling may need to be non-production devices in order to enable the execution and gathering of evidence. 

Test 1: The evaluator shall import or generate keys/secrets of each supported type according to the operational guidance. The evaluator shall write, or the developer shall provide access to, an application that generates a key/secret of each supported type and calls the import functions. The evaluator shall verify that no errors occur during import.

Test 2: The evaluator shall write, or the developer shall provide access to, an application that uses a generated or imported key/secret:

* For RSA, the secret shall be used to sign data. 
* For ECDSA, the secret shall be used to sign data.

The evaluator shall repeat this test with the application-imported or application-generated keys/secrets and a different application's imported keys/secrets or generated keys/secrets. The evaluator shall verify that the TOE requires approval before allowing the application to use the key/secret imported or generated by the user or by a different application: 

* The evaluator shall deny the approvals to verify that the application is not able to use the key/secret as described. 
* The evaluator shall repeat the test, allowing the approvals to verify that the application is able to use the key/secret as described.

[.line-through]#If the ST author has selected common application developer, this test is performed by either using applications from different developers or appropriately (according to API documentation) not authorizing sharing.#

[.line-through]#Test 3: The evaluator shall destroy keys/secrets of each supported type according to the operational guidance. The evaluator shall write, or the developer shall provide access to, an application that destroys an imported or generated key/secret. The evaluator shall repeat this test with the application-imported or application-generated keys/secrets and a different application's imported or generated keys/secrets. The evaluator shall verify that the TOE requires approval before allowing the application to destroy the key/secret imported by the administrator or by a different application:#

* [.line-through]#The evaluator shall deny the approvals and verify that the application is still able to use the key/secret as described.#
* [.line-through]#The evaluator shall repeat the test, allowing the approvals and verifying that the application is no longer able to use the key/secret as described.#

[.line-through]#If the ST author has selected common application developer, this test is performed by either using applications from different developers or appropriately (according to API documentation) not authorizing sharing.#


*2.2.8.1.3 Test*

If the TOE stores SDEs and authorization data inside the TSF, the evaluator shall ensure that external interfaces cannot extract this data in plaintext. 

In this case, use the evaluation activities of the FPT_PHP.3 if [.underline]#protected storage# is selected, FCS_COP.1/SK##C## if [.underline]#symmetric encryption using…# is selected, and FCS_COP.1/KAT if [.underline]#key wrapping using…# is selected.

If the TOE stores authentication data inside the operational environment, the evaluator shall ensure that plaintext data is not visible on the interface between the TOE and the operational environment.

*2.4.1.1.3 Test*

For each management function described in FMT_SMF[.line-through]##_EXT##.1.1, the evaluator shall perform the function with administrator authorization data and confirm it succeeds, and again with client application authorization data and confirm that it fails.

*2.5.4.1.3 Test*

*_Immutability_*

For immutable Root of Trust identity, the evaluator shall confirm a successful evaluation of [.line-through]#FPT_PHP.1 (Physical Protection)# #FPT_PHP.3 (Resistance to Physical Attack)#.

*_Mutability_*

For a mutable Root of Trust identity, the evaluator shall perform the following tests:

. Create or use an authenticated Root of Trust identity, confirm the authenticated method for modifying the Root of Trust identity succeeds.

. Create or use an unauthenticated Root of Trust identity, confirm the target fails to modify the Root of Trust identity.

== Tracking
https://github.com/DSC-iTC/cPP/issues/12[Issue #12]

https://github.com/DSC-iTC/cPP/issues/13[Issue #13]

https://github.com/DSC-iTC/cPP/issues/14[Issue #14]

https://github.com/DSC-iTC/cPP/issues/15[Issue #15]